"""empty message

Revision ID: c315d91b43e2
Revises: 
Create Date: 2022-10-11 17:35:02.119758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c315d91b43e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_username', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('post',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_userid', sa.Integer(), nullable=True),
    sa.Column('_title', sa.String(), nullable=False),
    sa.Column('_time', sa.DateTime(), nullable=False),
    sa.Column('_content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['_userid'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
