"""empty message

Revision ID: e06f7feee226
Revises: 
Create Date: 2022-10-12 13:28:22.980746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06f7feee226'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_userid', sa.String(), nullable=False),
    sa.Column('_username', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_userid', sa.String(), nullable=True),
    sa.Column('_title', sa.String(), nullable=False),
    sa.Column('_time', sa.DateTime(), nullable=False),
    sa.Column('_content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
